-- PostgreSQL 16+. Esquema inicial versionado, sem excluir historicos.
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE fontes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), sigla text NOT NULL UNIQUE CHECK(sigla IN ('EMOP','SINAPI','PROPRIA')), nome text NOT NULL);
CREATE TABLE publicacoes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), fonte_id uuid NOT NULL REFERENCES fontes(id), competencia date NOT NULL CHECK (EXTRACT(DAY FROM competencia)=1), uf char(2) NOT NULL, regime text NOT NULL CHECK(regime IN ('NAO_DESONERADO','DESONERADO','NAO_APLICAVEL')), revisao integer NOT NULL DEFAULT 1 CHECK(revisao>0), status text NOT NULL DEFAULT 'RASCUNHO' CHECK(status IN ('RASCUNHO','VALIDADA','PUBLICADA','REJEITADA')), arquivo_sha256 text, criado_em timestamptz NOT NULL DEFAULT now(), UNIQUE(fonte_id,competencia,uf,regime,revisao));
CREATE TABLE catalogo_itens (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), fonte_id uuid NOT NULL REFERENCES fontes(id), codigo text NOT NULL, tipo text NOT NULL CHECK(tipo IN ('SERVICO','INSUMO','COMPOSICAO_AUXILIAR')), UNIQUE(fonte_id,codigo,tipo));
CREATE TABLE itens_publicados (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), publicacao_id uuid NOT NULL REFERENCES publicacoes(id), item_id uuid NOT NULL REFERENCES catalogo_itens(id), descricao text, unidade text, preco numeric(20,6), situacao text NOT NULL CHECK(situacao IN ('INFORMADO','AUSENTE','NAO_PUBLICADO')), origem_arquivo text NOT NULL, origem_linha bigint, atributos jsonb NOT NULL DEFAULT '{}'::jsonb, UNIQUE(publicacao_id,item_id));
CREATE TABLE componentes_publicados (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), publicacao_id uuid NOT NULL REFERENCES publicacoes(id), pai_id uuid NOT NULL REFERENCES catalogo_itens(id), componente_id uuid REFERENCES catalogo_itens(id), codigo_componente_original text NOT NULL, sequencia text, coeficiente numeric(24,10), percentual numeric(24,10), origem_arquivo text NOT NULL, origem_linha bigint, UNIQUE(publicacao_id,pai_id,sequencia,codigo_componente_original));
CREATE TABLE lotes_importacao (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), publicacao_id uuid REFERENCES publicacoes(id), arquivo_nome text NOT NULL, arquivo_sha256 text NOT NULL, importador_versao text NOT NULL, status text NOT NULL, contagens jsonb NOT NULL DEFAULT '{}'::jsonb, erros jsonb NOT NULL DEFAULT '[]'::jsonb, criado_em timestamptz NOT NULL DEFAULT now());
CREATE TABLE obras (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), titulo text NOT NULL, descricao text, criado_em timestamptz NOT NULL DEFAULT now());
CREATE TABLE orcamentos (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), obra_id uuid NOT NULL REFERENCES obras(id), nome text NOT NULL, criado_em timestamptz NOT NULL DEFAULT now());
CREATE TABLE revisoes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), orcamento_id uuid NOT NULL REFERENCES orcamentos(id), numero int NOT NULL, status text NOT NULL DEFAULT 'ABERTA' CHECK(status IN ('ABERTA','FECHADA')), fechado_em timestamptz, UNIQUE(orcamento_id,numero));
CREATE TABLE etapas (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), revisao_id uuid NOT NULL REFERENCES revisoes(id), pai_id uuid REFERENCES etapas(id), titulo text NOT NULL, ordem int NOT NULL);
CREATE TABLE itens_orcamento (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), revisao_id uuid NOT NULL REFERENCES revisoes(id), etapa_id uuid REFERENCES etapas(id), publicacao_id uuid REFERENCES publicacoes(id), item_referencia_id uuid REFERENCES catalogo_itens(id), codigo_snapshot text NOT NULL, descricao_snapshot text NOT NULL, unidade_snapshot text NOT NULL, quantidade numeric(24,8) NOT NULL, custo_unitario_snapshot numeric(20,6) NOT NULL, bdi_percentual numeric(12,6) NOT NULL DEFAULT 0, preco_unitario_snapshot numeric(20,6) NOT NULL, total_snapshot numeric(22,2) NOT NULL, ordem int NOT NULL);
CREATE INDEX idx_itens_busca_codigo ON catalogo_itens(fonte_id,codigo);
CREATE INDEX idx_publicacoes_filtro ON publicacoes(fonte_id,competencia,uf,regime,status);
CREATE INDEX idx_componentes_pai ON componentes_publicados(publicacao_id,pai_id);
INSERT INTO fontes(sigla,nome) VALUES ('EMOP','Empresa de Obras Publicas RJ'),('SINAPI','Sistema Nacional de Pesquisa de Custos e Indices da Construcao Civil'),('PROPRIA','Composicoes proprias') ON CONFLICT DO NOTHING;
